from models.models import Flashcard, User
from data.q_and_a import data
import time
import random


users = []
python_stack = []

def sign_in():
    
    name: str = None
    username: str = None
    password_hash: str = None
    
    username = input("Choose your username: ")
    
    users.append(User(name, username, password_hash))
    
def create_cards_from_data(data_source):
    
    for datum in data_source:
        question = datum[0]
        answer = datum[1]
        card = Flashcard(question, answer)
        python_stack.append(card)
        
def ask_three_questions(stack):
    
    questions_asked = []
    
    for i in range(3):
        random_number = random.randint(0, len(stack) -1)
        if random_number not in questions_asked:
            questions_asked.append(random_number)
            
        index = questions_asked[-1]
        print("-" * 50)
        print(stack[index].question)
        time.sleep(2)
        
        print(stack[index].answer)
        time.sleep(3)

def main():

    create_cards_from_data(data)
    sign_in()
    new_user = users[0].username.title()
    print(f"Welcome {new_user}")
    time.sleep(1)
    print(f"{new_user}, you will be shown a series of three random questions" 
          "from a list of 20 questions generated by ChatGPT," 
          "followed by their answers")
    time.sleep(2)
    ask_three_questions(python_stack)
    print("*" * 50)
    print("The only purpose of this is to conceptualise a random selection of " 
          "questions. Eventually, they would be selected not randomly, but"
          "depending on their timed repetition pattern")
    
    
if __name__ == "__main__":
    main()
